config/routes.rb
Rails.application.routes.draw do

  #root
  root 'welcome#index', :as => 'home'
  post '/company/search', controller: 'companies', action: 'search', :as => 'search_company'

  #general
  post "/upload", controller: 'parsers', action: 'upload'
  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  resources :parsers

  #company
  get  '/company/new' => 'companies#new'
  get  '/company/:id' => 'companies#show', :as => 'company'
  post '/company/new' => 'companies#create', :as => 'create_company'
  post 'company/edit' => 'companies#edit', :as => 'edit_company'
  post '/company/update' => 'companies#update', :as => 'update_company'

  #users
  get   '/users/new'      => 'users#new'
  post  '/users/new'      => 'users#create', :as => 'create_user'
  get   '/users/:id'      => 'users#show', :as => 'user_show'
  get   '/users/edit/:id' => 'users#edit', :as => 'user_edit'

  patch '/users/update/', controller: 'users', action: 'update', :as => 'update_user'
  patch '/users/update/:id', controller: 'users', action: 'update_password', :as => 'update_user_password'
  patch '/users/destroy/', controller: 'users', action: 'destroy', :as => 'destroy_user_now'

  #survey
  post '/survey/new' => 'surveys#create'
  get   '/survey/new' => 'surveys#new'

  #option
  post '/option/new' => 'option#create'
  get   '/option/new' => 'option#new'

  #login
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  #ranking
  get 'ranking/grade/all' => 'rankings#grade_all', :as => 'ranking_grade'
  get 'ranking/response/all' => 'rankings#response_time_all', :as => 'ranking_response'
  post 'ranking/response/segment'  => 'rankings#segment_selected'

  #segment
  get '/segments/show_segments', controller: 'segments', action: 'show_segment', :as => 'segment'

  #management
  get 'management' => 'managements#index', :as => 'management_attach'
  get 'managements' => 'managements#company_denunciations', :as => 'management_company'

  #Comment
  post '/comment' => 'comments#create', :as=> 'create_comment'
  get '/comment/delete' => 'comments#destroy', :as => 'delete_comment'
  post '/comment/edit' => 'comments#edit', :as => 'edit_comment'


  #evaluation
  post '/company/show', controller: 'evaluations', action: 'rate', :as => 'rate'
  post '/company/response', controller: 'evaluations', action: 'response_time', :as => 'response_time'


  #topic
  resources :companies do
    resources :topics
  end

  resources :topics

  resources :attaches

  get 'management/attachs_approve', controller: 'attaches', action: 'approve', :as => 'approve'
  get 'management/attachs_reject', controller: 'attaches', action: 'reject', :as => 'reject'

  post '/topic_denunciation_create' => 'denunciations#create', :as => 'create_topic_denunciation'
  post '/topic_denunciation_destroy' => 'denunciations#destroy', :as => 'destroy_topic_denunciation'
  post '/comment_denunciation_create' => 'denunciations#create_for_comment', :as => 'create_comment_denunciation'

  #questions
  get '/questions/create'   =>  'questions#create', :as => 'create_questions'
  post'/questions/new'      => 'questions#new', :as => 'new_questions'
  #get '/questions/:id'      => 'questions#show', :as => 'questions_show'
  get '/questions/:id/results/' => 'questions#results',  :as => 'results_questions'

  #faq
  post 'company/faq', controller: 'faq', action: 'create', :as => 'faq'


  #resources :companies do
  #  resources :questions
  #end

  resources :questions


  #votes
  get '/votes' => 'votes#update', action: 'update', :as => 'update_vote'
  put '/votes' => 'votes#update'

  #company_denunciation
  post '/company_denunciation_create' => 'company_denunciations#create', :as => 'create_company_denunciation'
  post '/company_denunciation_destroy' => 'company_denunciations#destroy', :as => 'destroy_company_denunciation'
  get '/company_denunciation/show' => 'company_denunciations#show', :as => 'show_company_denunciation'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
	has_many :denunciations

	validates 	:description, :presence => { :message => 'Não é possível realizar um comentário vazio!' },length: { maximum: 150}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		comment = Comment.create(comment_params)
		redirect_to Topic.find(params[:comment][:topic_id])
	end

	def edit
		comment = Comment.find(params[:comment][:comment_id])
		edit_comment_params(comment)
		redirect_to Topic.find(comment.topic_id)
	end

	def destroy
		comment = Comment.find(params[:format])
		topic = comment.topic_id
		comment.denunciations.delete_all
		comment.destroy
		redirect_to Topic.find(topic)
	end
	

	private
		def comment_params
			params[:comment].permit(:description, :user_id, :topic_id)
		end

		def edit_comment_params(comment)
			comment.update_attributes(:description => params[:comment][:new_description])
		end
end

app/views/comments/_show.html.erb
<div class="container-comment container">
	<div class="col-lg-12 col-sm-12 text-center">
		<div class="well">
			<h4>Tem algo em mente? Comente</h4>
			<div class="input-group comment-field">
				<%= form_for(:comment, url: create_comment_path) do |form|%>
				<%= form.hidden_field :topic_id, :value =>@topic.id %>
				<%= form.hidden_field :user_id, :value =>current_user.id %>
				<%= form.text_area :description, :placeholder => "Escreva um comentário...", :maxlength => 150, :class	=> 'form-control input-sm chat-input comment-text-area', :id => 'userComment' %>
				</br>
				<span class="input-group-btn">
					<%= form.submit "Comentar",:class => "btn btn-primary btn-sm btn-comment"%>
				</span>
				<%end%>
			</div>
			</br>
			<ul data-brackets-id="12674" id="sortable" class="list-unstyled ui-sortable">
				<%if @comments.present?%>
				<% commentsQuantity = 0%>
				<% @comments.each do |comment|%>
				<% if commentsQuantity >= 6%>
				<div class="hidden_comments">
					<%end%>
					<strong class="pull-left primary-font"><%= User.find(comment.user_id).name%>:</strong>
					<small class="pull-right text-muted">

					<%if comment.user_id == current_user.id%>
					<div id="span-divs">
						<div class="dropdown-comment edit-<%= current_user.name%>-<%= comment.id%>" data-for=".cyruxx-<%= comment.id%>" 	id="<%= comment.id%>">
							<%= link_to image_tag("edit_comment_icon.png", size: "12x12", title: "Editar comentário"), remote: true %>&nbsp;
						</div>
						<div>
							
							<%= link_to image_tag("remove_icon.png", size: "12x12", title: "Deletar comentário"), delete_comment_path(comment.id), data: { confirm: "Tem certeza que deseja excluir o comentário?"}, :class=> 'dropdown-comment delete-'+current_user.name.split(" ")[0], :id => comment.id%>
						</div>
						
						<div>
							<% if current_user_comment_denunciation(comment.id) == nil %>
								<%= form_for(:session, url: create_comment_denunciation_path) do |f| %>
									<%= f.hidden_field :topic_id, :value => @topic.id %>
									<%= f.hidden_field :comment_id, :value => comment.id %>
									<%= f.hidden_field :user_id, :value => current_user.id %>
	     							&nbsp;
									<%= image_submit_tag("denunciation1.png", width: "12.5px", id: "denounce-comment"+comment.id.to_s, title: "Clique aqui para denuncia esse comentário", data: { confirm: "Tem certeza que deseja denunciar este comentário?" }) %>
								<% end %>
							<% else %>
								<%= form_for(:session, url: destroy_topic_denunciation_path) do |f| %>
									<%= f.hidden_field :denunciation_id, :value =>  current_user_comment_denunciation(comment.id).id %>
									<%= f.hidden_field :topic_id, :value => @topic.id %>
									&nbsp;
									<%= image_submit_tag("denunciation2.png", width: "12.5px",id: "destroy_denounce-comment"+comment.id.to_s, title: "Clique aqui para retirar a denúncia") %>
								<% end %>
							<% end %>
						</div>
					</div>
					<%end%>
					</small>
					</br>
					<li class="ui-state-default-comment">
						</br><%= comment.description%>
						</br>
						<h5><%= comment.created_at.to_formatted_s(:long)%></h5>
						<div class="row user-infos cyruxx-<%=comment.id%>">
							<div class="input-group comment-field">
								Edite seu comentário
								<%= form_for(:comment, url: edit_comment_path) do |form|%>
								<%= form.hidden_field :comment_id, :value => comment.id%>
								<%= form.text_area :new_description, :value => comment.description, :maxlength => 150, :class	=> 'form-control input-sm chat-input comment-text-area' %>
								<%= form.submit "Editar",:class => "btn btn-primary btn-sm btn-comment"%>
								<%end%>
							</div>
						</div>
					</li>
					<hr id="line-divisor">
					<% if commentsQuantity >= 6%>
						</div>
					<%end%>
				<% commentsQuantity = commentsQuantity + 1%>
				<%end%>
				<%if @comments.size > 6%>
				</br>
				<div id="hidden_comments_link">
					<li class="ui-state-default-comment"><a class="show_hidden_comments">Mostrar mais comentários </a></li>
				</div>
				<%end%>
				<%else%>
				</br></br>
				<li class="ui-state-default-comment" style="text-align:center">Não existe nenhum comentário. Seja o primeiro a comentar.</li>
				<%end%>
			</ul>
		</div>
	</div>
</div>
<script>
	var count = 0;
	$(".show_hidden_comments").click(function(){
	$(".hidden_comments").toggle("slow");
	if(count == 0){
	$(".show_hidden_comments").text("Ocultar comentários");
	count = 1;
	}else{
	$(".show_hidden_comments").text("Mostrar mais comentários");
	count = 0;
	}
});
	$(".user-infos").hide();
	$(".dropdown-comment").click(function() {
	var id = $(this).attr('id');
	var dataFor = $(this).attr('data-for');
	var idFor = $(dataFor);
	var currentButton = $(this);
	idFor.toggle("slow")
	});
</script>