config/routes.rb
Rails.application.routes.draw do

  #root
  root 'welcome#index', :as => 'home'
  post '/company/search', controller: 'companies', action: 'search', :as => 'search_company'

  #general
  post "/upload", controller: 'parsers', action: 'upload'
  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  resources :parsers

  #company
  get  '/company/new' => 'companies#new'
  get  '/company/:id' => 'companies#show', :as => 'company'
  post '/company/new' => 'companies#create', :as => 'create_company'
  post 'company/edit' => 'companies#edit', :as => 'edit_company'
  post '/company/update' => 'companies#update', :as => 'update_company'

  #users
  get   '/users/new'      => 'users#new'
  post  '/users/new'      => 'users#create', :as => 'create_user'
  get   '/users/:id'      => 'users#show', :as => 'user_show'
  get   '/users/edit/:id' => 'users#edit', :as => 'user_edit'

  patch '/users/update/', controller: 'users', action: 'update', :as => 'update_user'
  patch '/users/update/:id', controller: 'users', action: 'update_password', :as => 'update_user_password'
  patch '/users/destroy/', controller: 'users', action: 'destroy', :as => 'destroy_user_now'

  #survey
  post '/survey/new' => 'surveys#create'
  get   '/survey/new' => 'surveys#new'

  #option
  post '/option/new' => 'option#create'
  get   '/option/new' => 'option#new'

  #login
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  #ranking
  get 'ranking/grade/all' => 'rankings#grade_all', :as => 'ranking_grade'
  get 'ranking/response/all' => 'rankings#response_time_all', :as => 'ranking_response'
  post 'ranking/response/segment'  => 'rankings#segment_selected'

  #segment
  get '/segments/show_segments', controller: 'segments', action: 'show_segment', :as => 'segment'

  #management
  get 'management' => 'managements#index', :as => 'management_attach'
  get 'managements' => 'managements#company_denunciations', :as => 'management_company'

  #Comment
  post '/comment' => 'comments#create', :as=> 'create_comment'
  get '/comment/delete' => 'comments#destroy', :as => 'delete_comment'
  post '/comment/edit' => 'comments#edit', :as => 'edit_comment'


  #evaluation
  post '/company/show', controller: 'evaluations', action: 'rate', :as => 'rate'
  post '/company/response', controller: 'evaluations', action: 'response_time', :as => 'response_time'


  #topic
  resources :companies do
    resources :topics
  end

  resources :topics

  resources :attaches

  get 'management/attachs_approve', controller: 'attaches', action: 'approve', :as => 'approve'
  get 'management/attachs_reject', controller: 'attaches', action: 'reject', :as => 'reject'

  post '/topic_denunciation_create' => 'denunciations#create', :as => 'create_topic_denunciation'
  post '/topic_denunciation_destroy' => 'denunciations#destroy', :as => 'destroy_topic_denunciation'
  post '/comment_denunciation_create' => 'denunciations#create_for_comment', :as => 'create_comment_denunciation'

  #questions
  get '/questions/create'   =>  'questions#create', :as => 'create_questions'
  post'/questions/new'      => 'questions#new', :as => 'new_questions'
  #get '/questions/:id'      => 'questions#show', :as => 'questions_show'
  get '/questions/:id/results/' => 'questions#results',  :as => 'results_questions'

  #faq
  post 'company/faq', controller: 'faq', action: 'create', :as => 'faq'


  #resources :companies do
  #  resources :questions
  #end

  resources :questions


  #votes
  get '/votes' => 'votes#update', action: 'update', :as => 'update_vote'
  put '/votes' => 'votes#update'

  #company_denunciation
  post '/company_denunciation_create' => 'company_denunciations#create', :as => 'create_company_denunciation'
  post '/company_denunciation_destroy' => 'company_denunciations#destroy', :as => 'destroy_company_denunciation'
  get '/company_denunciation/show' => 'company_denunciations#show', :as => 'show_company_denunciation'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :company
	belongs_to :user
	has_many :comments
	has_many :denunciations
	before_create :set_create_date


#something it's wrong
=begin
	#title
	validates :title,
		presence: { :message => 'O título não pode estar vazio' }

	validates_length_of :title,
		:allow_blank => false,
		:within => 2..60,
		:too_short => 'O título deve ter no mínimo 2 caractres',
		:too_long => 'O título pode ter no máximo 60 caractres'

	#body
	validates :body,
		presence: { :message => 'O conteúdo não pode estar vazio' }

	validates_length_of :body,
		:allow_blank => false,
		:within => 2..1500,
		:too_short => 'O conteúdo deve ter no mínimo 2 caractres',
		:too_long => 'O conteúdo pode ter no máximo 1500 caractres'
=end


	private 
		def set_create_date
			self.create_date = Date.today
		end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	def new
		@topic = Topic.new
		@company = Company.new
		@company = Company.find(params[:company_id])
	end

	def create
		@topic = Topic.new(topic_params)
		@topic.user = current_user

		if @topic.save
			redirect_to @topic
		else
			render :new
		end
	end

	def show
		@topic = Topic.find(params[:id])
		@comments = @topic.comments.order('id DESC')
	end

	def edit
		@topic = Topic.find(params[:id])
		if current_user != @topic.user
			redirect_to @topic
		else
			#do nothing
		end
	end

	def update
		@topic = Topic.find(params[:id])

		if @topic.update_attributes(topic_params)
    		respond_to do |format| format.html {redirect_to :action => "show",:id => @topic.id}
	    		flash[:notice] = "Tópico atualizado"
	    	end	
    	end

	end


	def destroy
		topic = Topic.find(params[:id])
		company = topic.company

		if topic.destroy
	    	flash[:notice] = "Tópico excluído!"
	    	redirect_to company
    	end

	end

	def current_user_topic_denunciation
		Denunciation.find_by(topic_id: params[:id], user: current_user)
	end

	helper_method :current_user_topic_denunciation

	def current_user_comment_denunciation(comment_id)
		Denunciation.find_by(comment_id: comment_id, user: current_user)
	end

	helper_method :current_user_comment_denunciation

	private
		def topic_params
			params[:topic].permit(:title, :body, :company_id, :user_id)
		end
end

app/helpers/topics_helper.rb
module TopicsHelper

	# do not erase this helper

end

app/views/topics/edit.html.erb
<%= render "navbar/navbar" %>

<div id="erro-message">
		<% @topic.errors.messages.values.each do |msg| %>
		<% msg.each do |m| %>
		<li id="error_message"><%= m %></li>
			<%end %>
		<% end %>
		<% if flash[:error] -%>
			<p class="error"><%= flash[:error] %></p>
		<% end -%>
</div>
</br></br>


<div id="body-show-attach">
	<h1>Novo tópico</h1>
	</br>

	<%= form_for( @topic, url: {action: "update"} ) do |f| %>

	<%= f.hidden_field :company_id, :value => @topic.company.id %>

	<%= f.text_field :title, :placeholder => "Título do Tópico", :maxlength => 60, required: true, :class => "topic-field"%>
	</br></br>
	<%= f.text_area :body, :rows => 20, :cols => 59, :placeholder => "Conteúdo do tópico",
	:maxlength => 1500, required: true, :class => "topic-text", :maxlength => 254%>
	</br></br>

	<div id="button-new-topic">
		<%= button_tag(type: 'submit', class: "btn btn-confirm", id: 'btn-Confirmar') do %> Confirmar 
			<% end %><br/></br></br>
		<% end %>
	</div>

</div>
</section>

app/views/topics/new.html.erb
<%= render "navbar/navbar" %>

<div id="erro-message">
		<% @topic.errors.messages.values.each do |msg| %>
		<% msg.each do |m| %>
		<li id="error_message"><%= m %></li>
			<%end %>
		<% end %>
		<% if flash[:error] -%>
			<p class="error"><%= flash[:error] %></p>
		<% end -%>
</div>
</br></br>


<div id="body-show-attach">
	<h1>Novo tópico</h1>
	</br>

	<%= form_for( @topic, url: {action: "create"} ) do |f| %>

	<%= f.hidden_field :company_id, :value => @company.id %>

	<%= f.text_field :title, :placeholder => "Título do Tópico", :maxlength => 60, required: true, :class => "topic-field"%>
	</br></br>
	<%= f.text_area :body, :rows => 20, :cols => 59, :placeholder => "Conteúdo do tópico",
	:maxlength => 1500, required: true, :class => "topic-text", :maxlength => 254%>
	</br></br>

	<div id="button-new-topic">
		<%= button_tag(type: 'submit', class: "btn btn-confirm", id: 'btn-Confirmar') do %> Confirmar 
			<% end %><br/></br></br>
		<% end %>
	</div>

</div>
</section>

app/views/topics/show.html.erb
<%= render "navbar/navbar" %>
</br></br></br></br></br>
<div class = "form_attach">

	<p class="topic-title"><%= @topic.title %><p></br>
	<div class="description-topic">
		<p class="topic-username"><%= image_tag "file_topic.png"%> por: <b><%= @topic.user.name %></b></p>		
		<p class="topic-date"><%= image_tag "clock_topic.png", size: "15x15" %> <%= @topic.create_date.strftime("%d/%m/%Y, %T")  %></p>
	</div>

	</br></br></br><hr style="width:98%"></br></br>

	<div class="topic-body">
			<p><%= @topic.body %><p>
			<% if @topic.user == current_user %>
			<div class="position-topic-button">
				<%= link_to "Editar", edit_topic_path(@topic),  class: "btn btn-edit", id: "btn-edit-topic"%>
				<%= link_to "Excluir", @topic, data: { confirm: "Tem certeza que deseja excluir este tópico?" }, class: "btn btn-delete", id: "btn-delete-topic", method: :delete %>
			</div>
			<% end %>
			<div id="denunciation-topic-div">
				<% if current_user_topic_denunciation == nil %>
					<%= form_for(:session, url: create_topic_denunciation_path) do |f| %>
					<%= f.hidden_field :topic_id, :value => @topic.id %>
					<%= f.hidden_field :user_id, :value => current_user.id %>
					<%= image_submit_tag("denunciation1.png", id: "button-denunciation1", width: "5px", title: "Clique aqui para realizar uma denúncia", data: { confirm: "Tem certeza que deseja denunciar este tópico?" }) %>
					<p id="p-denunciation1">Denunciar</p>
					<% end %>
				<% else %>
					<%= form_for(:session, url: destroy_topic_denunciation_path) do |f| %>
					<%= f.hidden_field :denunciation_id, :value =>  current_user_topic_denunciation.id %>
					<%= f.hidden_field :topic_id, :value => @topic.id %>
					<%= image_submit_tag("denunciation2.png", id: "button-denunciation2") %>
					<p id="p-denunciation2" style="color:#4FBFD4">Retirar Denúncia</p>
					<% end %>
				<% end %>
			</div>
		<section class="comment-section">
			<%= render 'comments/show'%>
		</section>		
	</div></br>
	
</div>