config/routes.rb
Rails.application.routes.draw do

  #root
  root 'welcome#index', :as => 'home'
  post '/company/search', controller: 'companies', action: 'search', :as => 'search_company'

  #general
  post "/upload", controller: 'parsers', action: 'upload'
  post "/parsers", controller: 'parsers', action: 'index', :as => "index_parser"
  resources :parsers

  #company
  get  '/company/new' => 'companies#new'
  get  '/company/:id' => 'companies#show', :as => 'company'
  post '/company/new' => 'companies#create', :as => 'create_company'
  post 'company/edit' => 'companies#edit', :as => 'edit_company'
  post '/company/update' => 'companies#update', :as => 'update_company'

  #users
  get   '/users/new'      => 'users#new'
  post  '/users/new'      => 'users#create', :as => 'create_user'
  get   '/users/:id'      => 'users#show', :as => 'user_show'
  get   '/users/edit/:id' => 'users#edit', :as => 'user_edit'

  patch '/users/update/', controller: 'users', action: 'update', :as => 'update_user'
  patch '/users/update/:id', controller: 'users', action: 'update_password', :as => 'update_user_password'
  patch '/users/destroy/', controller: 'users', action: 'destroy', :as => 'destroy_user_now'

  #survey
  post '/survey/new' => 'surveys#create'
  get   '/survey/new' => 'surveys#new'

  #option
  post '/option/new' => 'option#create'
  get   '/option/new' => 'option#new'

  #login
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  #ranking
  get 'ranking/grade/all' => 'rankings#grade_all', :as => 'ranking_grade'
  get 'ranking/response/all' => 'rankings#response_time_all', :as => 'ranking_response'
  post 'ranking/response/segment'  => 'rankings#segment_selected'

  #segment
  get '/segments/show_segments', controller: 'segments', action: 'show_segment', :as => 'segment'

  #management
  get 'management' => 'managements#index', :as => 'management_attach'
  get 'managements' => 'managements#company_denunciations', :as => 'management_company'

  #Comment
  post '/comment' => 'comments#create', :as=> 'create_comment'
  get '/comment/delete' => 'comments#destroy', :as => 'delete_comment'
  post '/comment/edit' => 'comments#edit', :as => 'edit_comment'


  #evaluation
  post '/company/show', controller: 'evaluations', action: 'rate', :as => 'rate'
  post '/company/response', controller: 'evaluations', action: 'response_time', :as => 'response_time'


  #topic
  resources :companies do
    resources :topics
  end

  resources :topics

  resources :attaches

  get 'management/attachs_approve', controller: 'attaches', action: 'approve', :as => 'approve'
  get 'management/attachs_reject', controller: 'attaches', action: 'reject', :as => 'reject'

  post '/topic_denunciation_create' => 'denunciations#create', :as => 'create_topic_denunciation'
  post '/topic_denunciation_destroy' => 'denunciations#destroy', :as => 'destroy_topic_denunciation'
  post '/comment_denunciation_create' => 'denunciations#create_for_comment', :as => 'create_comment_denunciation'

  #questions
  get '/questions/create'   =>  'questions#create', :as => 'create_questions'
  post'/questions/new'      => 'questions#new', :as => 'new_questions'
  #get '/questions/:id'      => 'questions#show', :as => 'questions_show'
  get '/questions/:id/results/' => 'questions#results',  :as => 'results_questions'

  #faq
  post 'company/faq', controller: 'faq', action: 'create', :as => 'faq'


  #resources :companies do
  #  resources :questions
  #end

  resources :questions


  #votes
  get '/votes' => 'votes#update', action: 'update', :as => 'update_vote'
  put '/votes' => 'votes#update'

  #company_denunciation
  post '/company_denunciation_create' => 'company_denunciations#create', :as => 'create_company_denunciation'
  post '/company_denunciation_destroy' => 'company_denunciations#destroy', :as => 'destroy_company_denunciation'
  get '/company_denunciation/show' => 'company_denunciations#show', :as => 'show_company_denunciation'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :evaluations
    has_many :questions
    has_many :faq
    belongs_to :segment
    belongs_to :user
    has_many :topics
    has_many :attaches
    has_many :company_denunciations

    #validations to register a company
    #image logo
    has_attached_file :logo, styles: {default: "400x400#"}, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
    validates_attachment_file_name :logo, matches: /jpe?g\Z/
    validates_with AttachmentSizeValidator, attributes: :logo, less_than: 1.megabytes
    validates_attachment :logo, content_type: { content_type: "image/jpeg" }


    #name
    validates :name,
        presence: { :message => "Informe o nome da empresa" },
        uniqueness: { :message => "Uma empresa já foi cadastrada com esse nome" }    

    validates_length_of :name,
        :allow_blank => false,
        :within => 2..85,
        :too_short => 'O nome da empresa deve ter no mínimo 2 caracteres',
        :too_long => 'O nome da empresa deve ter no máximo 85 caracteres'

    #email
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email,
        :allow_blank => true,
        format: { with: VALID_EMAIL_REGEX, :message => 'Insira um e-mail válido' }

    #telephone
    validates :telephone,
        :allow_blank => true,
        numericality: { :message => "O telefone deve conter apenas números" }


    #address
    validates_length_of :address,
        :allow_blank => true,
        :within => 3..80,
        :too_short => 'O endereço deve ter no mínimo 3 caracters',
        :too_long => 'O endereço deve ter no máximo 80 caracters'

    #description
    validates_length_of :description,
        :allow_blank => true,
        :within => 0..500,
        :too_long => 'A descrição deve ter no máximo 500 caracters'

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

	# before_filter :authorize, only: [:create, :new]

	def new
		@company = Company.new()
		redirect_to login_path, alert: "Para cadastrar uma empresa é preciso estar logado" if current_user.nil?
	end

	def switchTypeImage(total)
		imageName = ""
		if total >= 4
			imageName = "gold_medal.png"
		elsif total <=3.99 && total >=2.49
			imageName = "silver_medal.png"
		else
			imageName = "bronze_medal.png"
		end
		return imageName
	end

	def show
		@company = Company.find(params[:id])
		if !@company.rate.nil?
			@total_evaluations = @company.rate
			@image_name = switchTypeImage(@total_evaluations)
		end
		if logged_in?
			@current_evaluation = current_user.evaluations.find_by(company_id: @company.id)
		end
	end

	def create
		@company = Company.new(company_params)
		@company.authenticated = false

		if @company.save
			flash[:notice] = 'Cadastro efetuado com sucesso!'
			redirect_to @company
		else
			render :new
		end
	end

	def edit
		@company = Company.find(params[:company][:id])
		if @company.user_id != current_user.id
			redirect_to home_path
		end
	end
	
	def update
		@company = Company.find(params[:company][:id])
		if @company.update_attributes(edit_company_params)
			flash[:notice] = 'Atributo atualizado com sucesso'
		else
			flash[:notice] = 'Erro ao atualizar o atributo!'
		end
		render :edit
	end

	def search
		@search_param = params[:current_search][:search]
  		@company = Company.where("name LIKE :search", :search => "%#{params[:current_search][:search]}%")
	end

	def company_params
		params[:company].permit(:name, :segment_id, :address, :telephone, :email, :description, :logo, :uf_id)
	end

	private
		def edit_company_params
			params[:company].permit(:name, :address, :telephone, :email, :description, :logo, :uf_id)
		end
end

app/helpers/companies_helper.rb
module CompaniesHelper

	def current_user_company_denunciation(company)
		CompanyDenunciation.find_by(user_id: current_user.id, company_id: company.id)
	end
end

app/views/companies/_faq_form_fields.html.erb
<li class = "control-group nested-fields">
		<div class="controls">
			<div class="for-questions-faq">
			<label for"question">Pergunta
      			<%= faq.text_field :question, :class => "input-for-pergunta", required: true%>
      		</label>
      		</div>
      		<label for="answer">Resposta
      		<%= faq.text_area :answer, :class => "input-for-pergunta", required: true%> 
      </label>  		
   	</div>
</li>

app/views/companies/new.html.erb
<%= render "navbar/navbar" %>
<section id="cadastrar_empresa">
	<%= image_tag("business_background.jpeg", :alt => "img", :class => "img") %>
	<section id="form_empresa">
		<h3>Cadastre sua Empresa</h3><br/><br/>

		<% if @company.errors.any? %>
			<ul>
				<% @company.errors.messages.values.each do |message|%>
					<% message.each do |m| %>
						<li id="error_message" style="color: #0B213A"> <%= m %> </li>
					<%end%>
				<%end%>
			</ul>
		<%end%><br/>

		<%= form_for @company, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>			

			<%= f.text_field :name , :placeholder => "Nome da Empresa", :maxlength => 50, :class => "form_control"%><br/><br/>

			<%= f.file_field :logo, :class => "form_control file_field" %></br>

			<%= f.select :segment_id, Segment.all.collect {|a| [a.name, a.id]}%></br></br>

			<%= f.text_field :address, :placeholder => "Endereço da Empresa", :maxlength => 80, :class => "form_control" %><br/><br/>

			<%= f.select :uf_id, Uf.all.collect {|uf| [uf.name, uf.id]}%><br/><br/>

			<%= f.text_field :telephone , :placeholder => "Telefone de Contato", :class => "form_control" %><br/></br/>

			<%= f.text_field :email , :placeholder => "E-mail da Empresa", :class => "form_control"%><br/><br/>

			<%= f.text_area :description,  :placeholder => "Descrição", :maxlength => 500, :id => "tarea" %><br/><br/>

			<%= button_tag(type: 'submit', class: "btn btn-primary") do %> Confirmar <% end %><br/>


			<br/></br/><br/></br/>

		<% end %>
	</section>
</section>
<section id="linear-new"></section>

app/views/companies/search.html.erb
<%= render "navbar/navbar" %>
<section id="corpo">
<section class="show-search">
    <div>

      <h1>Resultado da Busca</h1>

     	<%if @company.present? %>
     		<h2>Empresas encontradas com o termo "<%= @search_param%>"</h2>
			<% @company.each do |c|%>
				<p><%= link_to c.name, c %></p>
			<%end%>
		<%else%>
			<h2>Nenhuma Empresa encontrada com o termo "<%= @search_param%>".</h2>
		<%end%>

      </br></br></br>  
    </div>
<section>
</section>

app/views/companies/show.html.erb
<%= render "navbar/navbar" %>

<% if @company.logo_file_name == nil %>
	<%= image_tag("default_company_logo.png", :width => "125", :height => "125", :id => "image-company") %>
<%else%>
	<%= image_tag(@company.logo.url(:default), :width => "125", :height => "125", :id => "image-company") %>
<%end%>

<% if !@company.authenticated %>
<%= image_tag("no_verified.png", :width => "40", :height => "40", :id => "image-verified") %>
<%else%>
<%= image_tag("verified.png", :width => "40", :height => "40", :id => "image-verified") %>
<%end%>

<div id="name_company">
	<h1><%= @company.name %></h1>
</div>

<div id="info_empresa">
	<%= @company.telephone%><br />
	<%= @company.email %><br />
</div><br />

<% if @company.rate.present? %>
  <div id="general-rate">
    <h4>Nota geral da Empresa</h4> <br />
    <h4 id="value-rate"><%= number_with_precision(@total_evaluations, :precision => 2)  %></h4>
  </div>
  <div id="image-general-rate">
    <%= image_tag(@image_name, :width => "90", :height => "136.8", :id => "medal-image") %>
  </div>
<%end%>

<%if logged_in? %> 
  <% if !@company.authenticated %>
    <div id= "attach">
        <p><%= link_to "Solicitar Vínculo", new_attach_path(:company_id => @company.id), class: "btn btn-attach", id: "btn-vinculo" %> </p>
    </div>
  <%end%>
	<%if current_user.id == @company.user_id%>
		<%= form_for(:company, url: edit_company_path) do |form|%>
			<%= form.hidden_field :id, value: @company.id%>
			<p><%= form.submit 'Editar empresa',class: "btn btn-attach", id: "btn-edit" %></p>
		<%end%>
	<%end%>
 <%end%>

<% if logged_in? && current_user_company_denunciation(@company) == nil %>
  <div class="click-denuciatios">
  <%= link_to image_tag("denunciation1.png", id: "button-company-denunciation1", title: "Clique aqui para denunciar esta Empresa."), remote: true %>
  <p id="p-company-denunciation1">Denunciar</p>
  </div>
 <% elsif logged_in? %>
 	 <div class="click-denuciatios">
			<%= form_for(:session, url: destroy_company_denunciation_path) do |f| %>
			<%= f.hidden_field :company_denunciation_id, :value =>  current_user_company_denunciation(@company).id %>
			<%= f.hidden_field :company_id, :value => @company.id %>
			<%=image_submit_tag("denunciation2.png", id: "button-company-denunciation2", title: "Clique aqui para retirar sua denuncia sobre Empresa.", data: { confirm: "Tem certeza que deseja retirar sua denúncia sobre esta Empresa?"})%>
			<p id="p-company-denunciation2" style="color:#4FBFD4">Retirar Denúncia</p>
			<%end%>
	</div>
<% end %>
<p id="company-denunciation-count">Total de denúncias: <%= CompanyDenunciation.where(company_id: @company.id).count %></p>	
<div class="denuciations" id="denuciations">
	<% if logged_in? && current_user_company_denunciation(@company) == nil %>

		<%= form_for(:session, url: create_company_denunciation_path) do |f| %>
			<%= f.hidden_field :company_id, :value => @company.id %>
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<div id="description-denunciation">
				<label for"description">Justificativa
				<%=f.text_area :description%>
				</label>
				<%= f.submit "Confirmar denuncia", class: "btn btn-primary"%>

			</div>
		<% end %>
	<%end%>	
</div>

<div id="name_segment">
	<h2><%= @company.segment.name %></h2>
</div>

<div class="container-show-company">
	<div class="btn-group">
		<div class="btn avaliacao">Avaliações</div>
		<div class="btn geral">Geral</div>
		<div class="btn forum" id="js-btn-forum">Fórum</div>
		<div class="btn faq">FAQ</div>
		<div class="btn enquete" id="js-btn-enquete">Enquete</div>
	</div>

</div>

<section id="avaliacao">
	<div class="barra">
		<%if logged_in? %>
			<div class="estrelas">
				<div id="check-response">
					A empresa respondeu as reclamações?
					<form id="confirmation-response">
						<% if @current_evaluation.present? %>
							<%if @current_evaluation.response_time != nil%>
							Sim  <input type="radio" name="confirm-response" value="yes" class="response-radio" id="confirm-radio" checked>
							Não  <input type="radio" name="confirm-response" value="no" class="response-radio" id="decline-radio" disabled>
							<%else%>
								Sim  <input type="radio" name="confirm-response" value="yes" class="response-radio" id="confirm-radio" >
								Não  <input type="radio" name="confirm-response" value="no" class="response-radio" id="decline-radio" checked>
							<%end%>
						<%else%>
							Sim  <input type="radio" name="confirm-response" value="yes" class="response-radio" id="confirm-radio" >
							Não  <input type="radio" name="confirm-response" value="no" class="response-radio" id="decline-radio" checked>
						<%end%>
					</form>
				</div>
				<div class="evaluations-time">
				<span id="message-evaluation">
					Tempo de resposta da empresa:
				</span>
				<%= form_for(:response, url: response_time_path) do |f|%>
					<%= f.hidden_field :user_id, :value => current_user.id%>
					<%= f.hidden_field :company_id, :value => @company.id%>
					<% if @current_evaluation.present? %>
						<% if @current_evaluation.response_time != nil %>
							<%= f.number_field :response_time, :class => "response-time-field", :min => 0, :step => 1, :value => @current_evaluation.response_time%>
						<% else %>
							<%= f.number_field :response_time, :class => "response-time-field", :min => 0, :step => 1, :value => :min%>
						<% end %>
					<% else %>
						<%= f.number_field :response_time, :class => "response-time-field", :min => 0, :step => 1, :value => :min%>
					<%end%>
					<%= f.submit 'Submeter', :class => "btn btn-primary btn-sm btn-submit"%>
				<%end%>
				</div>
				<div class="evaluation-time">
					<span id="message-evaluation">
						Avaliação pessoal:
					</span>
					<% for rates in 1..5 do %>
						<%= form_for(:evaluations, url: rate_path) do |f|%>
							<%= f.hidden_field :grade, :value => rates%>
							<%= f.hidden_field :user_id, :value => current_user.id%>
							<%= f.hidden_field :company_id, :value => @company.id%>
							<%= f.submit 'Rates', :type => :image, :src => image_path("starpng.png"), :class => "star", :id=> 'star-'+rates.to_s%>
						<%end%>
					<%end%>
					</div>
				</div>
		<%else%>
			<p>Para avaliar uma empresa é necessário realizar login.</p>
		<%end%>
	</div>
</section>

<section id="forum">
   <div id="check-response">
        <div class="list-forum">
        	<ul class="nav nav-list">
        		<% @company.topics.each do |topic| %>
            		<li><%= link_to topic.title, topic%></li>
            <% end %> 
            </ul>
            <%= hidden_field :company_id, :value => @company.id%>
        </div>
      
		<div class="">
  			<%if logged_in?%>
    			<p><%= link_to "Novo tópico", new_topic_path(:company_id => @company.id), class: "btn btn-primary" %> </p>
  			<%end%>
  		</div>	
          
    </div>
</section>
<section id="faq">
		<div id="faq-create">
	    	<%= form_for(:faq, url: faq_path) do |faq|%>
	      		<div class="field">
	    			<h3>Para adicionar perguntas clique no link abaixo</h3>
	    			<div class="btn adicionar">Adicionar outra pergunta</div>
	    				<div class="faq-questions">
	    					<fieldset id="options-questions" >
	   		 					<%= faq.hidden_field :company_id, :value => @company.id%>
	      						<ol>
	        					<%= render partial: "faq_form_fields", locals: {faq: faq} %>
	      						</ol>
	   		 				</fieldset>
	    					<div class="actions">
	    						<%= faq.submit "Criar", :id => "button"%>
	      					</div>
	      				</div>
	      		</div>
	      	<%end%>
	    </div>
    <% @company.faq.each do |faqs| %>
    <div id="faq-body">
	    <div class="well col-sm-12 col-md-8">
	        <div class="row user-row">
	          <div class="col-md-10 title-segment">
	           <strong><%=faqs.question%></strong><br>
	          </div>
	          <div class="col-md-2 dropdown-user" data-for=".cyruxx-<%=faqs.id%>" id="<%=faqs.id%>">
	            (<span style="color: #FF4040">resposta</span>)<%= image_tag("down.png", :alt => "abrir", :class => "img-down ") %>
	          </div>
	        </div>
	        <div class="row user-infos cyruxx-<%=faqs.id%>">
	          <div class="col-sm-10 col-md-10 col-md-offset-1">
	            <div class="panel panel-primary">
	              <div class="panel-heading">
	                <h3 class="panel-title">Resposta</h3>
	              </div>
	              <div class="panel-body">
	                <div class="row">
	                  <div class="col-md-10">
	                      <span><%=faqs.answer%></span>
	                  </div>
	                </div>
	              </div>
	            </div>
	          </div>
	        </div>
	      </div>
      </div>
 <% end %>
</section>
<section id="enquete">
	<div id="enquete-body">
		<div class="header-body-enquete">
			<%if logged_in?%>
				<%= form_for(:question, url: new_questions_path) do |form|%>
       				 <%= form.hidden_field :company_id, value: @company.id%>
        			<span><%= form.submit 'Criar enquete',class: "btn btn-attach", id: "btn-edit" %></span>
        		<%end%>
  			<%end%>
  		</div>	
        <div id="list-questions">
         	<% @company.questions.each do |questions| %>
            	<ul class="nav nav-list">
                	<li><%= link_to questions.title, questions%></li>
                </ul>

            <% end %>
            <%= hidden_field :company_id, :value => @company.id%>

  		</div>
  	</div>
</section>

<section id="description">
	<% if @company.description == nil || @company.description == "" %>
	<p>Essa empresa não possui uma descrição.</p>
	<%else%>
	<p><%= @company.description %></p>
	<%end%>
</section>

<script>
	$("#button-company-denunciation1").click(function(){
		$("#description-denunciation").toggle("slow");
	});

	<%if @current_evaluation.present? %>
	var current_rate  =  <%= @current_evaluation.grade%>;
	if(current_rate >= 0){
		for (var i = 0; i < current_rate; i++) {
			$('.star:eq('+i+')').addClass('full');
		}
	}
	<%end%>
	var selecionado = document.getElementById("decline-radio").checked;
	if (selecionado) {
		$(".response-time-field").attr("disabled", true);
		$(".btn-submit").attr("disabled", true);
	}

	$("#decline-radio").click(function(){
		$(".response-time-field").attr("disabled", true);
		$(".btn-submit").attr("disabled", true);
	});
	$("#confirm-radio").click(function(){
		$(".response-time-field").attr("disabled", false);
		$(".btn-submit").attr("disabled", false);
	});

	$(".avaliacao").click(function(){
		$("#description").hide("slow");
		$("#forum").hide("slow");
		$("#faq").hide("slow");
		$("#enquete").hide("slow");
		$("#denuciations").hide("slow");
		$("#avaliacao").show("slow");
	});
	$(".adicionar").click(function(){
		$(".faq-questions").toggle("slow");
	});
	$(".geral").click(function(){
		$("#avaliacao").hide("slow");
		$("#forum").hide("slow");
		$("#faq").hide("slow");
		$("#enquete").hide("slow");
		$("#denuciations").hide("slow");
		$("#description").show("slow");
	});
	$(".forum").click(function(){
		$("#avaliacao").hide("slow");
		$("#faq").hide("slow");
		$("#description").hide("slow");
		$("#enquete").hide("slow");
		$("#denuciations").hide("slow");
		$("#forum").show("slow");
	});
	$(".faq").click(function(){
		$("#avaliacao").hide("slow");
		$("#forum").hide("slow");
		$("#description").hide("slow");
		$("#enquete").hide("slow");
		$("#denuciations").hide("slow");
		$("#faq").show("slow");
	});

	$(".enquete").click(function(){
		$("#description").hide("slow");
		$("#forum").hide("slow");
		$("#faq").hide("slow");
		$("#avaliacao").hide("slow");
		$("#denuciations").hide("slow");
		$("#enquete").show("slow");
	});
	$("#button-company-denunciation1").click(function(){
		$("#description").hide("slow");
		$("#forum").hide("slow");
		$("#faq").hide("slow");
		$("#avaliacao").hide("slow");
		$("#enquete").hide("slow");
		$("#denuciations").show("slow");
		
	});

	$('.star').on('click', function(){
		var ponto = $(this).attr('id');
		for (var i = 0; i <= indice; i++) {
			$('.star:eq('+i+')').addClass('full');
		}
	});
	$('.star').on('mouseover', function(){
		var indice = $('.star').index(this);
		$('.star').removeClass('full');
		for (var i = 0; i <= indice; i++) {
			$('.star:eq('+i+')').addClass('full');
		}
	});
	$('.star').on('mouseout', function(){
		var indice = $('.star').index(this);
		for (var i = 0; i <= indice; i++) {
			$('.star:eq('+i+')').removeClass('full');
		}
		<%if @current_evaluation.present? %>
		var current_rate  =  <%= @current_evaluation.grade%>;
		if(current_rate >= 0){
			for (var i = 0; i < current_rate; i++) {
				$('.star:eq('+i+')').addClass('full');
			}
		}
		<%end%>
	});
	var img_current = 0;
  		$(".user-infos").hide();
  		$(".dropdown-user").click(function() {
    		var id = $(this).attr('id');
    		var dataFor = $(this).attr('data-for');
    		var idFor = $(dataFor);
    		var currentButton = $(this);
    		idFor.slideToggle(400, function() {
      			if(img_current == 0){
          		currentButton.html('(<span style="color: #FF4040">esconder</span>)<%= image_tag("up.png", :alt => "abrir", :class => "img-down")%>');
          		img_current =1;
      		}else{
        		currentButton.html('(<span style="color: #FF4040">resposta</span>)<%= image_tag("down.png", :alt => "abrir", :class => "img-down")%>');
        		img_current = 0;
      		}
		});
  	});
</script>